from locust import HttpUser, task, between
import json

class LoadTestUser(HttpUser):
    @task
    def post_prediction(self):
        json_data = {
            "inputs":[
                {
                    "name":"is_explicit",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        1.0
                    ]
                },
                {
                    "name":"duration_ms",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.27927992323571016
                    ]
                },
                {
                    "name":"danceability",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.9089068825910931
                    ]
                },
                {
                    "name":"energy",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.472935276552163
                    ]
                },
                {
                    "name":"key",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.09090909090909091
                    ]
                },
                {
                    "name":"loudness",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.7477259841743289
                    ]
                },
                {
                    "name":"mode",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        1.0
                    ]
                },
                {
                    "name":"speechiness",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.08425624321389794
                    ]
                },
                {
                    "name":"acousticness",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.010735492809498851
                    ]
                },
                {
                    "name":"instrumentalness",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.0
                    ]
                },
                {
                    "name":"liveness",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.13183279742765275
                    ]
                },
                {
                    "name":"valence",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.2157258064516129
                    ]
                },
                {
                    "name":"tempo",
                    "shape":[
                        1,
                        1
                    ],
                    "datatype":"FP32",
                    "data":[
                        0.42839339231137696
                    ]
                }
            ]
        }
        self.client.post(
            "/v2/models/jukebox/infer",
            json=json_data,
        )